"""empty message

Revision ID: 9fa5b63b898f
Revises: 7660391f4287
Create Date: 2022-05-09 23:55:38.019421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fa5b63b898f'
down_revision = '7660391f4287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('nick_name', sa.String(length=64), nullable=True),
    sa.Column('info_y', sa.String(length=2), nullable=False),
    sa.Column('ur_box', sa.Integer(), nullable=True),
    sa.Column('upd_dt', sa.DateTime(), nullable=False),
    sa.Column('ins_dt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('members')
    op.add_column('menu', sa.Column('upd_dt', sa.DateTime(), nullable=False))
    op.add_column('menu', sa.Column('ins_dt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'ins_dt')
    op.drop_column('menu', 'upd_dt')
    op.create_table('members',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.TEXT(), nullable=True),
    sa.Column('info_y', mysql.VARCHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('member')
    # ### end Alembic commands ###
