"""empty message

Revision ID: ba06f679b971
Revises: 9fa5b63b898f
Create Date: 2022-05-09 23:58:15.985187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba06f679b971'
down_revision = '9fa5b63b898f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crossfit_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('bizno', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('upd_dt', sa.DateTime(), nullable=False),
    sa.Column('ins_dt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crossfit_box')
    # ### end Alembic commands ###
